on: 
  workflow_dispatch:
  push:


jobs:
  testitout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Print current directory
        run: |
          pwd && ls
      
      - uses: osbm/kaggle-login@test-composite
        with:
          KAGGLE_USERNAME: osmanf
          KAGGLE_KEY: test
